name: tdd_generator
description: TDD folder structure generator. Create basic folders and some fundamental dart files for your flutter project
version: 0.0.1
repository: https://github.com/bobobekturdiyev/tdd_generator

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
   path: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
